
package com.css.component.epic;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSInterfaceService", targetNamespace = "http://ws.ss.ncs.com/", wsdlLocation = "file:/C:/Users/tao/Desktop/query.wsdl")
public class WSInterfaceService
    extends Service
{

    private final static URL WSINTERFACESERVICE_WSDL_LOCATION;
    private final static WebServiceException WSINTERFACESERVICE_EXCEPTION;
    private final static QName WSINTERFACESERVICE_QNAME = new QName("http://ws.ss.ncs.com/", "WSInterfaceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/tao/Desktop/query.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSINTERFACESERVICE_WSDL_LOCATION = url;
        WSINTERFACESERVICE_EXCEPTION = e;
    }

    public WSInterfaceService() {
        super(__getWsdlLocation(), WSINTERFACESERVICE_QNAME);
    }

    public WSInterfaceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSINTERFACESERVICE_QNAME, features);
    }

    public WSInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, WSINTERFACESERVICE_QNAME);
    }

    public WSInterfaceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSINTERFACESERVICE_QNAME, features);
    }

    public WSInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WSInterfacePort")
    public WSInterface getWSInterfacePort() {
        return super.getPort(new QName("http://ws.ss.ncs.com/", "WSInterfacePort"), WSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WSInterfacePort")
    public WSInterface getWSInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.ss.ncs.com/", "WSInterfacePort"), WSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSINTERFACESERVICE_EXCEPTION!= null) {
            throw WSINTERFACESERVICE_EXCEPTION;
        }
        return WSINTERFACESERVICE_WSDL_LOCATION;
    }

}
